DROP TABLE USER;
DROP TABLE BOOK;
DROP TABLE AUTHOR;
DROP TABLE BOOKAUTHOR;
DROP TABLE CATALOGUE;
DROP TABLE LEDGER;
CREATE TABLE USER (
    userID: INT NOT NULL,
    userName: VARCHAR(255),
);

CREATE TABLE BOOK (
    bookID: INT NOT NULL,
    title: VARCHAR(255),
    ISBN: INT NOT NULL,
);

CREATE TABLE AUTHOR (
    authorID: INT,
    firstName: VARCHAR(255),
    lastName: VARCHAR(255)
);

CREATE TABLE BOOKAUTHOR (
    bookID INT NOT NULL,
    authorID INT NOT NULL,
    CONSTRAINT FK_bookID FOREIGN KEY (bookID) REFERENCES BOOK(bookID),
    CONSTRAINT FK_authorID FOREIGN KEY (authorID) REFERENCES AUTHOR(authorID)
);

CREATE TABLE CATALOGUE (
    catalogueID: INT,
    bookID: INT,
    nrCopies: INT,
    CONSTRAINT FK_bookID FOREIGN KEY (bookID) REFERENCES BOOK(bookID)
)

CREATE TABLE LEDGER (
    transID: INT NOT NULL,
    userID: INT NOT NULL,
    bookID: INT NOT NULL
    returnDate: DATE,
    CONSTRAINT FK_bookID FOREIGN KEY (bookID) REFERENCES BOOK(bookID),
    CONSTRAINT FK_userID FOREIGN KEY (userID) REFERENCES USER(userID)
);